# Generated by Django 5.2.7 on 2025-11-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="has_sent",
        ),
    ]
